//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_semilleros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        public int idActividad { get; set; }
        public int idFase { get; set; }
        public string nombreActividad { get; set; }
        public string descripcionActividad { get; set; }
        public System.DateTime fechaInicioActividad { get; set; }
        public Nullable<System.DateTime> fechaFinActividad { get; set; }
        public string estadoActividad { get; set; }
        public Nullable<int> tiempoEstimadoHoras { get; set; }
        public string prioridadActividad { get; set; }
    
        public virtual Fases Fases { get; set; }
    }
}
