//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_semilleros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evento()
        {
            this.PatrocinadoresEventos = new HashSet<PatrocinadoresEventos>();
            this.ProyectoEvento = new HashSet<ProyectoEvento>();
        }
    
        public int idEvento { get; set; }
        public string nombreEvento { get; set; }
        public string lugarEvento { get; set; }
        public string descripcionEvento { get; set; }
        public System.DateTime fechaEvento { get; set; }
        public System.TimeSpan horaEvento { get; set; }
        public string estadoEvento { get; set; }
        public bool estadoRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatrocinadoresEventos> PatrocinadoresEventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoEvento> ProyectoEvento { get; set; }
    }
}
