//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_semilleros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fases()
        {
            this.Actividad = new HashSet<Actividad>();
        }
    
        public int idFase { get; set; }
        public int idProyecto { get; set; }
        public string nombreFase { get; set; }
        public string descripcionFase { get; set; }
        public System.DateTime fechaInicioFase { get; set; }
        public Nullable<System.DateTime> fechaFinFase { get; set; }
        public string estadoFase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividad> Actividad { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
