//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_semilleros.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gestion_de_semilleroEntities1 : DbContext
    {
        public Gestion_de_semilleroEntities1()
            : base("name=Gestion_de_semilleroEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividad> Actividad { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Fases> Fases { get; set; }
        public virtual DbSet<Patrocinadores> Patrocinadores { get; set; }
        public virtual DbSet<PatrocinadoresEventos> PatrocinadoresEventos { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
        public virtual DbSet<ProyectoEvento> ProyectoEvento { get; set; }
        public virtual DbSet<Reunion> Reunion { get; set; }
        public virtual DbSet<Semillero> Semillero { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
