//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_semilleros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patrocinadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patrocinadores()
        {
            this.PatrocinadoresEventos = new HashSet<PatrocinadoresEventos>();
        }
    
        public int idPatrocinador { get; set; }
        public string nombrePatrocinador { get; set; }
        public string tipoPatrocinador { get; set; }
        public string telefonoPatrocinador { get; set; }
        public int montoAportePatrocinador { get; set; }
        public string correoPatrocinador { get; set; }
        public bool estadoRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatrocinadoresEventos> PatrocinadoresEventos { get; set; }
    }
}
