//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_semilleros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoEvento
    {
        public int idProyecto { get; set; }
        public int idEvento { get; set; }
        public Nullable<System.DateTime> fechaVinculacion { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
