//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_semilleros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyecto()
        {
            this.Fases = new HashSet<Fases>();
            this.ProyectoEvento = new HashSet<ProyectoEvento>();
        }
    
        public int idProyecto { get; set; }
        public int idSemillero { get; set; }
        public string nombreProyecto { get; set; }
        public System.DateTime fechaInicioProyecto { get; set; }
        public string objetivoProyecto { get; set; }
        public Nullable<System.DateTime> fechaFinProyecto { get; set; }
        public string estadoProyecto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fases> Fases { get; set; }
        public virtual Semillero Semillero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoEvento> ProyectoEvento { get; set; }
    }
}
