//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_semilleros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reunion
    {
        public int idReunion { get; set; }
        public int idSemillero { get; set; }
        public string temaReunion { get; set; }
        public System.DateTime fechaReunion { get; set; }
        public System.TimeSpan horaReunion { get; set; }
        public string estadoReunion { get; set; }
        public string urlReunion { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
    
        public virtual Semillero Semillero { get; set; }
    }
}
