//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_semilleros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int idUsuario { get; set; }
        public Nullable<int> idSemillero { get; set; }
        public string nombreUsuario { get; set; }
        public string rolUsuario { get; set; }
        public string contraseñaUsuario { get; set; }
        public string CorreoUsuario { get; set; }
    
        public virtual Semillero Semillero { get; set; }
    }
}
